version: '3'
services:
  db:
    container_name: mariadb
    build: ./config/database
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=drupal
    ports:
      - "33066:3306"
    volumes:
      - portfolio-db:/var/lib/mysql
    networks:
      - portfolio-network

  drupal:
    container_name: drupal
    depends_on: 
      - db
    build: ./cms/drupal
    environment:
      - MYSQL_DATABASE="drupal"
      - MYSQL_HOSTNAME="db"
      - MYSQL_PASSWORD="password"
      - MYSQL_PORT=33066
      - MYSQL_USER="root"
      - MYSQL_PREFIX="drupal_"
      - ENVIRONMENT_NAME='Local'
      - ENVIRONMENT_BGCOLOR='#064771'
      - ENVIRONMENT_FGCOLOR='#FFFFFF'
    ports:
      - "8080:80"
    networks:
      - portfolio-network

volumes:
  portfolio-db:

networks:  
  portfolio-network: