version: '3'
services:
  db:
    container_name: mariadb
    build: ./config/database
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=drupal
    ports:
      - "33066:3306"
    volumes:
      - portfolio-db:/var/lib/mysql
    networks:
      - portfolio-network

volumes:
  portfolio-db:

networks:  
  portfolio-network: